upstream auth-billing {
    server auth-billing.example.com;
}

upstream geniess {
    server geniess.example.com;
}

upstream entity {
    server entity.example.com;
}

server {
    listen 80;
    server_name your_server_name;

    location /api/ {
        proxy_pass http://auth-billing;
    }

    location /geniess/ {
        proxy_pass http://geniess;
    }

    location /entity/ {
        proxy_pass http://entity;
    }
}